# Generated by Django 5.1.2 on 2024-10-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_staff_alter_appointment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_appointments', to='appointments.staff'),
        ),
    ]
