# Generated by Django 5.1.2 on 2024-10-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='available_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('staff', 'available_date', 'start_time', 'end_time')},
        ),
    ]
