# Generated by Django 5.1.2 on 2024-10-15 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_availability_available_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='available_date',
            new_name='end_date',
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('staff', 'start_date', 'end_date', 'start_time', 'end_time')},
        ),
    ]
